### ISSUE TITLE
Releasing the LD reference

### ISSUE THREAD

**Issue by carbocation** [statgen/localzoom#11]
Currently when you click on a SNP and select 'Make LD Reference', it seems that the SNP stays the LD reference no matter what else you do. E.g., if you type a new SNP into the 'Go to region' search, the other SNP is still the LD reference. 

Assuming I didn't miss part of the interface, it would be great to have a way to de-select that SNP as the LD reference.

**Comment by abought** [comment]
Thanks for the bug report! You have spookily good timing- a fix for this was posted to the development branch of LocusZoom.js about an hour ago. My next goal will be to integrate the changes into LocalZoom. 

Since it's part of a larger body of work, this may take 1-2 weeks. In the interim, if you are comfortable with doing something "developer-ish", you can manually clear the reference variant via the browser javascript console. With the LocalZoom plot open, this would be something like:

`lz_plot_1.state.ldrefvar = null ; lz_plot_1.applyState();`

**Comment by carbocation** [comment]
Fantastic! Thank you - the console command works nicely. Glad that I submitted an already-fixed bug, makes life easier for everyone ;-)

**Comment by abought** [comment]
The newest localzoom release incorporates this and other bugfixes. (sorry for the delay- we added a bunch of other features too, like BED files and user-provided PLINK LD)
