### ISSUE TITLE
Stating the expected headers

### ISSUE THREAD

**Issue by carbocation** [statgen/localzoom#13]
In the [locuszoom document about preparing data](https://my.locuszoom.org/about/#prepare-data), which is linked from localzoom, the specific names of the expected data columns are not stated. It would be useful to list the names that can be automatically detected, so that we can more easily tell how to munge our file headers for easy compatibility with localzoom.

**Comment by abought** [comment]
I've made some improvements to the parser to handle the EBI format since our last conversation. I'll close this ticket for now.

There really isn't one exhaustive header list (because our parser tries to be flexible), so I think overly prescriptive docs might not be the way to go. 

If anyone thinks that their file format could stand to be better supported, feel free to reach out with a list of example headers and we could try to improve the auto-detect features. Otherwise, I hope the example files and notes are useful. :)
