### ISSUE TITLE
How to change the LDserver setting

### ISSUE THREAD

**Issue by psytky03** [statgen/localzoom#19]
Hi! 
I would like to use an in-house LDserver, how could I change the settings?

**Comment by abought** [comment]
Greetings! Apologies for not seeing this question sooner.

I wasn't aware that anyone was forking this particular repo! But strictly speaking, you could change [this URL](https://github.com/statgen/localzoom/blob/fbe95d129e6a70c184e2a08da403cea5d582980d/src/util/constants.js#L2), assuming that you are running an instance of [Michigan LDServer software](https://github.com/statgen/ldserver) that exposes a particular API.

(Since this is a standalone app that makes certain assumptions about our LD server, certain other things are hardcoded and might take more spelunking to change- most notably the list of LD populations in the "choose LD population" dropdown)
https://github.com/statgen/localzoom/blob/fbe95d129e6a70c184e2a08da403cea5d582980d/src/util/constants.js#L2


If you want to customize the plot, without all the extra point-and-click UI contrls of LocalZoom, the core plotting widget is [LocusZoom.js](https://github.com/statgen/locuszoom), which offers detailed docs and examples for talking to your own data provider or tabix files.

**Comment by abought** [comment]
An alternative would be to add your own LD from plink-output LD calculations, using a tabix file. It's a much more restrictive workflow, so if you're comfortable running your own UM LD server, that is definitely a more powerful approach.

I'll close this ticket for now but feel free to follow up with any further questions.
