### ISSUE TITLE
Default to same settings when loading multiple tracks?

### ISSUE THREAD

**Issue by carbocation** [statgen/localzoom#9]
I might have missed a way that already exists to do this, but I'm frequently loading several tracks which were usually built on the same platform (BOLT, etc). It would be convenient if it were possible to indicate that the data follow the same pattern as the most recently loaded track (e.g., which column is the effect size, allele frequency, etc).

**Comment by abought** [comment]
Hey there! As I clean out older tickets:

If you're still using this tool, feel free to reach out any time with a sample of file headers. We try to auto-detect file formats/ column headers wherever possible so things just work.

Remembering format options would be a nice improvement in the future. We've tried to be a little conservative with our guessing logic in case someone mixed two file formats, like the use case of comparing their analysis to something from the GWAS catalog. (eg, we don't want someone ever making a picture with the wrong columns). 

We apply a number of heuristics for our "guess" logic, but once those options are overridden, an incorrect column spec could change the meaning of data. Hence the manual step, and hence our interest in improving auto-detection rather than a strictly rigid "remember" feature.
